version: "3.7"
services:
  app:
    build: .
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
